# Generated by Django 5.1.1 on 2024-10-16 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_distribution_distributionrecord_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="address",
        ),
    ]
