# Generated by Django 5.1.1 on 2024-10-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_employee_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
