# Generated by Django 5.1.1 on 2024-10-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_batch_date_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stage",
            options={"ordering": ["stage_number"]},
        ),
        migrations.AlterField(
            model_name="stage",
            name="stage_number",
            field=models.IntegerField(unique=True),
        ),
    ]
