# Generated by Django 5.1.1 on 2024-10-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_stage_options_alter_stage_stage_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="barcode",
            field=models.ImageField(
                blank=True, null=True, upload_to="equipment/barcodes/"
            ),
        ),
    ]
