# Generated by Django 5.1.1 on 2024-10-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_logintable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="barcode",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="barcode",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="distributionrecord",
            name="barcode",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="barcode",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="barcode",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacility",
            name="barcode",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="barcode",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stage",
            name="barcode",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sterilizationmethod",
            name="barcode",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="storagerecord",
            name="barcode",
            field=models.TextField(blank=True, null=True),
        ),
    ]
